language: node_js
node_js:
  - 8

deploy:
  provider: firebase
  token:
    secure: uHDrj+oM6QnzyMiqLQZ0LxzZo02i/BUvk06Tobs3T0cCObIfXpsfXfyz/wDLFI4+8DWSoxPHmNSjkGAziZcTnS/IpY4EK2fTzDkWwy22U3EeMEWPKOwIB4nf7XjnmjWVFEQxK1l2ghJp33v5gP3mjlZ2eUe22fTeIs//xtge3ZJwQHffC7i+jdFJWUu/tGN7chwBRElhfxW4Gx4ewbozyyb3fZrP8qk6Lk0cQLDzQjKu8VyskoK+ycSCIlW0f30FTuzdVX9CDn5oiFUTJSYVSnL19X1Y9vUBq/8gc0WZvB2Np6kA/2ISl2PWrfbshaMC2CH4VAPpiBbkfzoyeaNGSkbnnCmLcgj1YbaRyE3VbTXEWmKJ/jxyuwYcXAE4CRYWMZ3dXUU5fyW+YoqH2/er1wEsAcTFbqvU/aLWvjXoR0n8w4cZ+1Pt8xRtQqB/drmUX8YzNVv72x78QRQEjmS/SW3DTett5pQcYc0nCWCL4OFXy5b/ud2Us2pjSaNYre3zAmr4xR9F7/3wcfhO86h2WKKyVSrBJ3RYjPV+V6X3hzaedIWEi1H8Aaj6sszny1BAesXm5JLOHFcq89yY2aQEWCLIJd636TkSjnZw1fOevJN3mCOr++qDWGdgB5Gv0Dc7pIK+fBQcZw5cbkgQ19TyO6ejZFMVhH2s1WHQM2JTB8s=
  project: techheaven-general