language: node_js
node_js:
- 8
deploy:
  provider: firebase
  token:
    secure: miwcqiRPaxDt4Yl3z2tXyBKwPUH8Tu7PcGJzjEkTqjncUlqKWp11SZGS59QeNms1cdeAGJyGDnBoypx3e+dMhqcmnNBxnIfm1WeBwAz7C5H6UgksjWclLQRKe/1U+JYQU83gk4J9Q3RqMMPdTojNnpP+zlBYTqrQfCM3d1etrdZrFNWuVB1JOrZPmOgLpjlSotv/QJKogLvae6UmAVkicjI9TmTF7DnYrzPOZRO/Ef5vTraTUuLA+LctS7F/siaTrCbBfr2p3EP5205kEf+fHMl7Q4AlkP3T58D5TyYXf+SIzYo4oOG73x8YYPSW5DWa9FLNjfYm3EYpCgnnQ2i3Nu2PTz8ifnlr/Ohw/qhGRSBvIxBPSeNrBePHAh7VUEMuc8BoShFT3KQwlDXYRKGKTNtIHTY81W0PF8EclNKwqP8cXuZxxakXPJtvLCY0MqpAFyS110KG4+M3cuaXqylpXr8Bp58sBUesU5n2X8J3kXDdZP9RN6aFkWh5Tna0mQO2EaNJDMJ5mRmg7NANGBOFNJhu2U/UdXAfiMnKWPT9kHrGtOqFUVUSlT9MSXUL+Cq3ZtuvFbGsFcAN6Va0/aoEeSsRK3PRHhdxwFU7tbufOTUiOtRQjP0vGJH+m49MtN+rZjVhIgZOBSeoO1FDJmZ1Xq3lxZzZ+K7Dsb0IUzfQbOo=
  project: techheaven-general